apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mynginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    - name: infra
        repoURL: 'https://github.com/fdaluisio/infra-repo.git'
        path: randomquotes-java
        targetRevision: HEAD
        helm:
          valueFiles:
            - values.yaml
    - name: config
        repoURL: 'https://github.com/fdaluisio/config-repo.git'
        path:
        targetRevision: HEAD
        helm:
          valueFiles:
            - values.yaml
  syncPolicy: {}
    syncOptions:
      - CreateNamespace=true
